FROM openjdk:8u121-jdk-alpine

RUN apk update && \
	apk add --no-cache curl gettext jq py-pip && \
	pip install mcstatus

WORKDIR minecraft

ARG PROJECT_ID=stratus-181519
ARG BRANCH=master
ARG URL=https://storage.googleapis.com/artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH/.m2
ARG VERSION=1.12.2-SNAPSHOT
ARG SPORTBUKKIT_VERSION=1.12.2-R0.1-SNAPSHOT

ADD $URL/tc/oc/sportbukkit/$SPORTBUKKIT_VERSION/sportbukkit-$SPORTBUKKIT_VERSION.jar server.jar

WORKDIR plugins

ADD $URL/tc/oc/api-ocn/$VERSION/api-ocn-$VERSION.jar api-ocn.jar
ADD $URL/tc/oc/api-bukkit/$VERSION/api-bukkit-$VERSION.jar api.jar
ADD $URL/tc/oc/commons-bukkit/$VERSION/commons-bukkit-$VERSION.jar commons.jar
ADD $URL/tc/oc/Lobby/$VERSION/Lobby-$VERSION.jar lobby.jar
ADD $URL/tc/oc/PGM/$VERSION/PGM-$VERSION.jar pgm.jar
ADD $URL/net/anxuiz/Tourney/$VERSION/Tourney-$VERSION.jar tourney.jar
ADD $URL/com/github/rmsy/Channels/Channels/1.9-SNAPSHOT/Channels-1.9-SNAPSHOT.jar channels.jar
ADD $URL/me/anxuiz/bukkit-settings/1.9-SNAPSHOT/bukkit-settings-1.9-SNAPSHOT.jar settings.jar
ADD $URL/tc/oc/raven-bukkit/1.11-SNAPSHOT/raven-bukkit-1.11-SNAPSHOT.jar raven.jar
ADD $URL/other/protocolsupport.jar protocol.jar
# TODO: CommandBook, ChatModerator, ...
ADD https://dev.bukkit.org/projects/worldedit/files/latest worldedit.jar
ADD https://dev.bukkit.org/projects/buycraft/files/latest buycraft.jar

WORKDIR ..
